alecthomas/kingpin

guesswidth_unix.go

* guesswidth_unix.go: Check the env to see if the fd width should be
overridden with the COLUMNS var
Signed-off-by: Jeff Mickey <j@codemac.net>

COLUMNS overrides fd width

---

cmd.go
model.go
templates.go
usage_test.go

Add support for hidden commands.
Note: I'm aware that if all the commands are hidden the usage may be ugly because I don't remove the commands header in this case. But I fail to see the meaning/need for that so I rather not complicate the code for no good reason.

Support hidden commands

---

app.go
app_test.go
parser.go

Sometime there is a need to force flags to come before positional arguments.
My use case is that I have a run subcommand that basically run a script. Instead of forcing the end user to write something like:
app run script -- -x arg1 arg2...
With the use of OptionsFirst, the end user can simply write
app run script -x arg1 arg2...
The change is quite minimal and by default does nothing

Added OptionsFirst - the ability to force option to come before all positional arguments

---

app.go
args_test.go
flags_test.go

At the moment, if you register the application version (with `app.Version(<version>)`) but also register required flags/args, `--version` does not work on its own. Instead, it will complain that required flags/arguments are not provided.
From an end-user perspective, it doesn't make sense to have to provide these just to display the version, because it will just ignore them anyway (all it does is print the version and exit).
This PR ensures `--version` works even in the presence of required arguments.

Make --version ignore missing required flags/arguments

---

app.go

Currently --help flag is ignored if arguments are parsed using non-default parser (using kingpin.New() instead of kingpin.CommandLine).

Fix --help flag when using non-global Application

---

README.md

For this part of the README:
`kingpin.CommandLine.HelpFlag.Short('-h')`
go1.5 gives me: `illegal rune literal`
Compiled without errrors only this way:
`kingpin.CommandLine.HelpFlag.Short('h')`
Fixed corresponding part of the README.

Update README (CommandLine.HelpFlag.Short part)

---

flags_test.go
parsers.go
values.go
values.json
values_generated.go

Added support and test for regular expressions as flag/argument values.
I didn't add the `RegexList*` family of functions since I didn't figure they'd be that useful. Can easily add to  `values.json` if desired.

Added support for regexp flags

---

guesswidth_ae.go
guesswidth_unix.go

Add the proper build constraints to avoid the use of `syscall` when build is for appengine.

Make code build in appengine

---

flags.go
flags_test.go

My interpretation of the current [`.Envar()` contract](https://github.com/alecthomas/kingpin/blob/1895ce4fc0d6d75c01a7f1a728571250c7da6866/flags.go#L269-L270)... I can't think of a use case where `.Defaut()` should have precedence, otherwise it's just impossible to use env vars on a flag with a default value.

prefer user-defined env var value over application-hardcoded defaults

---

templates.go

With the current code, I see something like this on my command usage:
```
usage: tool command [<flags>]
Do Command
Flags:
--help                     Show context-sensitive help (also try
--help-long and --help-man).
--version                  Show application version.
Subcommands:
```
Notice there are no subcommands but I see the header anyway.  Not sure if text/template changed the boolean truthiness of an empty slice, but adding a "len" in front of it seems to fix it:
```
usage: tool command [<flags>]
Do Command
Flags:
--help                     Show context-sensitive help (also try
--help-long and --help-man).
--version                  Show application version.
```

fix dangling "Subcommands:" on command help usage

---

README.md
app.go
app_test.go
cmd.go
cmd_test.go
completions.go
completions_test.go
examples/completion/main.go
flags.go
flags_test.go
parser.go
templates.go

I've implemented deep bash completion integration within the library. Work towards #75.  A bash completion script can call into any tool using Kingpin by using a new flag `--help-bash-completion` as the first argument, followed by subsequent user-entered arguments. 
Opening this PR to get some eyes on it, and see how it can be improved. Happy to add docs once we're happy with the overall structure of it (Since this does bring some new API):
- `type HintAction func(args []string) []string` A new type `HintAction`, a function that returns a list of options for completions.
- `func (a *ArgClause) HintAction(action HintAction) *ArgClause` to register a `HintAction` to call when completions are requested for an argument.
- `func (a *ArgClause) HintOptions(options ...string) *ArgClause` to …

Add Bash Completion Support

---

README.md

The flag to generate man pages was changed in c553ee39c6b336f00108d7e13b736cf1dd97a2f2 from `--man-page` to `--help-man`. This just updates the Readme to reflect that.

Fix readme instructions for generating man page

---

.travis.yml
README.md
cmd/genvalues/main.go
templates.go
usage.go

The text/template package now supports whitespace trimming.
https://golang.org/doc/go1.6#template

Switch to text/template from Go 1.6

---

app.go
app_test.go
args.go
cmd.go
cmd_test.go
parser.go

This change handles autocompleting scenarios like `program command <tab>` where `command` has arguments with completion options or an action-fn. For ex, if git used kingpin, `git checkout <tab>` could complete branch names.

Autocomplete a command's args

---

flags.go
flags_test.go
parser.go

To solve #146
Modified `func (f *FlagClause) Short(name rune) *FlagClause` to use rune instead of byte.
Modified `func (p *ParseContext) Next() *Token` to parse runes if arg is short flag instead of byte.

Parse short argument as rune not as byte to support unicode characters

---

README.md

This makes clear that the parsers aforementioned are not the only ones included with kingpin, and are only examples.

Add link to parsers.go in README.md

---

README.md

When trying out the examples noticed a missing newline.

Added newline to example in README

---

parser.go
parser_test.go

Fixes https://github.com/alecthomas/kingpin/issues/191.
The problem was that `p.args` is always modified to contain the *remaining* tokens, rather than all the tokens. We don't need to cross-reference `p.argi` because the current token (the @file to be expanded) has already been removed.

Fix bug when mixing @file with other args or flags

---

README.md

The HintAction example in the README has the wrong function signature

Fix README HintAction function signature

---

app.go
app_test.go
cmd.go
model.go
parser.go
parser_test.go
usage_test.go

Also introduces a helper function in the ParseContext that determines
if a ParseElement is the currently executing command.

Add optional subcommands

---

README.md

The "count" number in simple example was incorrect.

Fix README: Simple example count.

---

_examples/completion/main.go

This was the only example not importing from gopkg. When trying multiple examples this one would not work because it was not available locally. It took me a while to understand what was happening.

Import from gopkg like the other examples

---

app.go
clause.go
clause_test.go
model.go
parser.go
struct.go

As discussed in #208 and on gitter: This PR implements a method for populating flags from an user-defined external source, such as a config file. Some properties:
- This source has lower priority than flags set on the command-line, and envars. 
- Multiple resolvers can be added, and they will be used in the order added, until the first match is found. 
- The lookup is performed using the name of the flag, unless the user sets a custom one. 
- It is possible to disable usage of the resolvers on a per-flag basis.
Things I'm not sure about and would appreciate some discussion around:
- Currently it is not possible to add a resolver directly on a flag. I don't see that this would be useful, but it wouldn't be hard to add if there is a use-case?
- I did not check in any implementations for …

Implement a config resolver

---

app.go

When `--help` is passed, there is no need to set and validate default
flags/arguments, since we are just going to print the usage text and
exit.
This fixes #218.

Fix setDefaults to exit early on `--help`

---

model.go

As completion- and help-flags are not ignored when parsed in FlagSummary(), ```[<flags>]``` token will always be displayed in usage line even if there are no more possible flags to choose from.

Don't show additional-flags token in usage if all flags are required

---

templates.go

* Complete file names when there are no matches.
* Convert to a native Zsh completion script .
* Don't call `compinit`. That is up to the user. Calling it resets the completion system.
* Quote array expansion with `@` to avoid dropping empty entries.
* The Zsh completion script can both be `eval`-ed and installed into `fpath`.

Improve the shell completion templates

---

go.mod
go.sum

Using the latest current versions of the template and units packages.
Test dependencies are included too.
Fixes #253.

all: convert to a Go module

---

app.go
usage.go
usage_test.go

Hi,
I had a usecase (https://github.com/secrethub/secrethub-cli/pull/71) where I'd like to have some extra functions available in the usage template. How do you feel about making it possible to add some custom functions?

Add possibility to use custom functions in the usage template

---

usage.go

This fixes the behaviour of formatCmdUsage
- before: it outputs the apps flags and arguments
- after: it outputs the commands flags and arguments
Template file to test:
``` tmpl
{{define "FormatCommands"}}\
{{range .FlattenedCommands}}
{{template "FormatUsage" .}}\
{{end}}\
{{end}}\
\
{{define "FormatUsage"}}
{{if .Help}}\
{{.Help|Wrap 0}}\
{{end}}\
{{end}}\
\
{{if not .Context.SelectedCommand}}\
{{template "FormatUsage" .App}}
{{end}}
{{if .Context.Flags}}
Flags:
{{.Context.Flags|FlagsToTwoColumns|FormatTwoColumns}}
{{end}}
{{if .Context.Args}}
Args:
{{.Context.Args|ArgsToTwoColumns|FormatTwoColumns}}
{{end}}
{{if .Context.SelectedCommand}}
{{if len .Context.SelectedCommand.Commands}}
Subcommands:
{{template "FormatCommands" .Context.SelectedCommand}}
{{end}}\
{{else if .App.Commands}} …
```

usage: fix formatCmdUsage

---

app.go
app_test.go

fixes issue reported in https://github.com/alecthomas/kingpin/issues/260
the included test fails prior to this change because validation is called before the values have been set.

app: fix premature validation

---

cmd.go
model.go
usage_test.go

This can for example be used to display a longer help text in the command-specific help than in the apps root help.

Add a long command help text to the usage template context

---

envar.go

Directly return the string slice returned by Split, no need to
wrap this in another slice.

Don't wrap string slice in another

---

args_test.go
flags_test.go

Don't assign a value to err if we don't end up checking it.

Remove ineffectual assignments in tests

---

args.go
model.go
usage.go

This is for example useful when a command accepts an argument for
backwards compatability purposes only. As in this case the argument
is no longer the recommended way to do things, it should not be
included in the usage output.

Add possibility to hide arguments from usage/help

---

args.go
model.go
templates.go
usage.go

Just like you can set a placeholder for flags, you can now set
a placeholder for arguments, to be used in the help of the command
instead of the arg name.
This can for example be used for compound arguments; To set the
placeholder to list all parts, e.g.: `<first>[:<second>]`

Add PlaceHolder functionality for arguments

---

args.go
cmd.go
flags.go

Maybe someone wants to change the default help messages (e.g. of the `--version` flag), than this adds the opportunity to do so.

Add setter for help message

---

templates.go

zsh's compinit only considers files where the absolute first line starts with #compdef or #autoload [1]. Kingpin was generating completion files with a leading newline, causing this logic to skip the file.
[1]: https://github.com/zsh-users/zsh/blob/27a64a16fb5407c64ff190f2af5182797ac048a8/Completion/compinit#L503-L504

Remove newline before #compdef

---

parsers.go
values.go

I'm fed up with implementing "MarhsalXXX", "Stringer", etc, etc...
kingpin requires "Value" interface to parse string
even though there's cool interface "encoding.TextUnmarshaler".

Support encoding.Text(Unm|M)arshaler

---

cmd.go

The Go runtime would panic at the following line because of an out-of-bounds slice access if autocompletion was requested for a clause that consumed the remainder of a command:
https://github.com/alecthomas/kingpin/blob/cf44c60659e38b5559aa885c13ad76c9bd6e8d50/cmd.go#L35
By specifically checking for these kinds of clauses, the problem should be mitigated.
**Example**
```golang
package main
import "github.com/alecthomas/kingpin"
func main() {
var strings []string
kingpin.Arg("test", "").StringsVar(&strings)
kingpin.Parse()
}
```
```
$ go run main.go --completion-bash 1 2  
panic: runtime error: index out of range [1] with length 1
```

Fix autocompletion of args that consume remainder

---

app.go
app_test.go
parser.go

If a `--` argument is passed, from then on only arguments should be parsed. This is already handled correctly in most places, but autocompleting did not honour this yet.
**Example**
```golang
package main
import "github.com/alecthomas/kingpin"
func main(){
kingpin.Arg("arg1", "").String()
kingpin.Flag("flag1", "").String()
kingpin.Flag("flag2", "").String()
kingpin.Parse()
}
```
If this following command is executed:
```
go run main.go --completion-bash an-argument --flag1 --  --
```
We expect not to get a suggestion for any of the flags of the command because the `--` argument signals that all arguments were provided. However, on the current `master`, the result is:
```sh
$ go run main.go --completion-bash an-argument --flag1 --  --
--help
--flag1
--flag2
```
If there is a more elegant …

Honour -- delimiter in autocompletion

---

usage.go

The only way to set a boolean flag as "false" is to include the flag with the `no-` prefix. This fact is not documented anywhere, making it difficult for people to know how to disable a flag.

document bool flag option

---

go.mod
go.sum
values.go

Use the open source package str2duration (which is a wrapper)
around time.ParseDuration, to parse duration args from strings.
This package supports more time formats, including days and weeks.
This closes #328

Extend DurationVar() to support days, weeks

---

cmd/genvalues/main.go
go.mod
go.sum
templates.go
usage.go
usage_test.go

I am interested in removing the github.com/alecthomas/template dependency because the upgrade from Unicode 13 to Unicode 15 triggers a test failure: https://go.googlesource.com/go/+/def0be5e34d6657c84407c8afe4ace05d10d1848
Instead of relying on this old copy, switch to text/template. The whitespace trimming was added in Go 1.6:
https://go.dev/doc/go1.6#template
I generated this change using `M-x replace-string }}\ -}}`

Switch to text/template with trim whitespace directive

---

app.go
app_test.go

When the version flag is passed, the application should do nothing but print the version and exit. But currently, the pre-action for the version flag gets executed AFTER the default for all the other flags are set.
Setting defaults involves validation like checking for file's existence etc. These validation are not necessary when the --version flag is passed. This PR fixes that
```go
var (
config = kingpin.Flag("config", "path to config").Short('c').Default("config.yaml").ExistingFile()
)
func main() {
kingpin.Version("0.0.1")
kingpin.Parse()
// ...
}
```
Would throw this error:
```
➜  go run . --version
main: error: path 'config.yaml' does not exist, try --help
exit status 1
```

Handle --version just like --help

---

templates.go

Sub-commands and sub-commands flags are not autocompleted correctly in ZSH.
This is because in the ZSH template, the argument passed to `--completion-bash` begins with the command name.
The issue can be reproduced in `_examples/completion`: running `./completion nc -- ` returns identical autocompletion values as the `./completion -- ` alone.
Incorrect invocation of `--completion-bash` with the command name:
```sh
grzegorz@mbp kingpin % ./completion --completion-bash ./completion nc -- 
--help
--flag-1
--flag-2
```  
Fixed invocation of `--completion-bash` without the command name:
```sh
grzegorz@mbp kingpin % ./completion --completion-bash nc --             
--nop-flag
--host
--port
--format
--host-with-multi
--host-with-multi-options
--format-with-override-1
--format-with-override-2 …
```

Do not pass command name to `--completion-bash` argument in ZSH template

---

go.mod
go.sum

It seems like renovate is not updating the `go.sum` correctly.
Superseds #352

Bump github.com/alecthomas/units

---

renovate.json5

Adds options to run `go mod tidy` after an update and to update import paths in case there's a major update of a dependency.

Update renovate config to run go mod tidy
